//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.24 at 08:39:42 PM TRT 
//


package io.github.susimsek.services.organization.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.github.susimsek.services.organization.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.github.susimsek.services.organization.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateOrganizationRequest }
     * 
     */
    public CreateOrganizationRequest createCreateOrganizationRequest() {
        return new CreateOrganizationRequest();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link CreateOrganizationResponse }
     * 
     */
    public CreateOrganizationResponse createCreateOrganizationResponse() {
        return new CreateOrganizationResponse();
    }

    /**
     * Create an instance of {@link GetAllOrganizationsRequest }
     * 
     */
    public GetAllOrganizationsRequest createGetAllOrganizationsRequest() {
        return new GetAllOrganizationsRequest();
    }

    /**
     * Create an instance of {@link GetAllOrganizationsResponse }
     * 
     */
    public GetAllOrganizationsResponse createGetAllOrganizationsResponse() {
        return new GetAllOrganizationsResponse();
    }

    /**
     * Create an instance of {@link GetOrganizationByIdRequest }
     * 
     */
    public GetOrganizationByIdRequest createGetOrganizationByIdRequest() {
        return new GetOrganizationByIdRequest();
    }

    /**
     * Create an instance of {@link GetOrganizationByIdResponse }
     * 
     */
    public GetOrganizationByIdResponse createGetOrganizationByIdResponse() {
        return new GetOrganizationByIdResponse();
    }

}
