//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.25 at 09:29:05 PM TRT 
//


package io.github.susimsek.demo.services.department.model;

import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.github.susimsek.demo.services.department.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@NoArgsConstructor
public class ObjectFactory {

    /**
     * Create an instance of {@link GetOrganizationByIdRequest }
     * 
     */
    public GetOrganizationByIdRequest createGetOrganizationByIdRequest() {
        return new GetOrganizationByIdRequest();
    }

    /**
     * Create an instance of {@link GetOrganizationByIdResponse }
     * 
     */
    public GetOrganizationByIdResponse createGetOrganizationByIdResponse() {
        return new GetOrganizationByIdResponse();
    }

}
