//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.25 at 09:29:05 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://susimsek.github.io/organizations", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.github.susimsek.demo.services.department.model;
